# Generated by Django 3.1.1 on 2020-11-11 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0005_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
